 version: '3'
    
 services:
    db:
      image: 'postgres: latest'
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./db:/var/lib/postgresql/data
      ports:
        - "5432:5432"
    app:
      build: .
      command: python main.py
      volumes:
        - ./code:/code
      depends_on:
        - db